core:
  - changed-files:
      - any-glob-to-any-file:
          - packages/gensx-core/**

package:
  - changed-files:
      - any-glob-to-any-file:
          - packages/gensx-*/**

cli:
  - changed-files:
      - any-glob-to-any-file:
          - packages/gensx/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - website/docs/**

homepage:
  - changed-files:
      - any-glob-to-any-file:
          - website/home/**

examples:
  - changed-files:
      - any-glob-to-any-file:
          - examples/**
