packages:
  - "packages/*"
  - "examples/*"
  - "extensions/*"
  - "docs"
  - "website/docs"
  - "website/home"
  - "!**/dist"

catalog:
  "@rollup/plugin-commonjs": "^25.0.7"
  "@rollup/plugin-node-resolve": "^15.2.3"
  "@rollup/plugin-typescript": "^11.1.6"
  "@types/glob": "^8.1.0"
  "@types/react": "^18.3.20"
  "@vitest/coverage-istanbul": "^3.2.3"
  "eslint-plugin-n": "17.19.0"
  "glob": "^10.3.10"
  "gray-matter": "^4.0.3"
  "ink": "^5.2.1"
  "nodemon": "^3.1.10"
  "openai": "^4.104.0"
  "rollup": "^4.42.0"
  "tsx": "^4.19.2"
  "typescript": "^5.7.2"
  "vite": "^6.3.5"
  "vitest": "^3.2.3"
  "zod-to-json-schema": "^3.24.1"
  "zod": "3.25.56"

catalogs:
  examples:
    "@types/node": "^20"
  packages:
    "@types/node": "^18"
