packages:
  - "packages/*"
  - "examples/*"
  - "docs"
  - "website/docs"
  - "website/home"
  - "!**/dist"

catalog:
  "@rollup/plugin-commonjs": "^25.0.7"
  "@rollup/plugin-node-resolve": "^15.2.3"
  "@rollup/plugin-typescript": "^11.1.6"
  "@types/glob": "^8.1.0"
  "@vitest/coverage-istanbul": "^2.1.8"
  "eslint-plugin-n": "^17.16.2"
  glob: "^10.3.10"
  gray-matter: "^4.0.3"
  nodemon: "^3.1.9"
  openai: "^4.87.4"
  rollup: "^4.39.0"
  tsx: "^4.19.2"
  typescript: "^5.7.2"
  vite: "^6.2.2"
  vitest: "^2.1.8"
  zod-to-json-schema: "^3.24.1"
  zod: "^3.24.2"

catalogs:
  examples:
    "@types/node": "^22"
  packages:
    "@types/node": "^18"
