packages:
  - "packages/*"
  - "examples/*"
  - "docs"
  - "website/docs"
  - "website/home"

catalog:
  "@types/node": "^20.17.23"
  "@vitest/coverage-istanbul": "^2.1.9"
  nodemon: "^3.1.9"
  openai: "^4.85.4"
  tsx: "^4.19.2"
  typescript: "^5.8.2"
  vitest: "^2.1.9"
  zod-to-json-schema: "^3.24.3"
  zod: "^3.24.2"
