packages:
  - "packages/*"
  - "examples/*"
  - "docs"
  - "website/docs"
  - "website/home"
  - "!**/dist"

catalog:
  "@types/glob": "^8.1.0"
  "@vitest/coverage-istanbul": "^2.1.9"
  "eslint-plugin-n": "^17.16.2"
  glob: "^10.3.10"
  gray-matter: "^4.0.3"
  nodemon: "^3.1.9"
  openai: "^4.89.0"
  tsx: "^4.19.2"
  typescript: "^5.7.2"
  vite: "^5.4.14"
  vitest: "^2.1.9"
  zod-to-json-schema: "^3.24.5"
  zod: "^3.24.2"

catalogs:
  examples:
    "@types/node": "^20"
  packages:
    "@types/node": "^18"
