name: Build GenSX Example Workflows

on:
  pull_request:
    paths:
      - "examples/client-side-tools/gensx/**"
      - "examples/chat-ux/gensx/**"
      - "examples/draft-pad/gensx/**"
      - "examples/deep-research/gensx/**"

jobs:
  build-workflows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow:
          - "examples/client-side-tools"
          - "examples/chat-ux"
          - "examples/draft-pad"
          - "examples/deep-research"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node ⚙️
        uses: ./.github/actions/setup-node
        with:
          version: 22.x

      - name: Build Workflow
        run: |
          npx gensx@latest build ${{ matrix.workflow }}/gensx/workflows.ts
