name: Deploy GenSX Example Workflows

on:
  push:
    branches: [main]
    paths:
      - "examples/client-side-tools/gensx/**"
      - "examples/chat-ux/gensx/**"
      - "examples/draft-pad/gensx/**"
      - "examples/deep-research/gensx/**"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changes.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed examples
        id: changes
        run: |
          # For pushes to main, compare against the previous commit
          BASE_SHA="HEAD~1"
          CURRENT_SHA="HEAD"

          echo "Comparing $BASE_SHA..$CURRENT_SHA"

          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only "$BASE_SHA" "$CURRENT_SHA")
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Initialize matrix array
          MATRIX='[]'

          # Check each example directory
          if echo "$CHANGED_FILES" | grep -q "examples/client-side-tools/gensx/"; then
            MATRIX=$(echo "$MATRIX" | jq '. += ["examples/client-side-tools"]')
            echo "Detected changes in client-side-tools"
          fi

          if echo "$CHANGED_FILES" | grep -q "examples/chat-ux/gensx/"; then
            MATRIX=$(echo "$MATRIX" | jq '. += ["examples/chat-ux"]')
            echo "Detected changes in chat-ux"
          fi

          if echo "$CHANGED_FILES" | grep -q "examples/draft-pad/gensx/"; then
            MATRIX=$(echo "$MATRIX" | jq '. += ["examples/draft-pad"]')
            echo "Detected changes in draft-pad"
          fi

          if echo "$CHANGED_FILES" | grep -q "examples/deep-research/gensx/"; then
            MATRIX=$(echo "$MATRIX" | jq '. += ["examples/deep-research"]')
            echo "Detected changes in deep-research"
          fi

          echo "Final matrix: $MATRIX"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  deploy-workflows:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.matrix != '[]'
    strategy:
      matrix:
        workflow: ${{ fromJson(needs.detect-changes.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Workflow
        id: deploy
        uses: ./.github/actions/deploy-gensx
        with:
          org: gensx
          working_directory: ${{ matrix.workflow }}
          environment_name: prod
          api_key: ${{ secrets.GENSX_API_KEY }}
          workflow_file: gensx/workflows.ts
          env: |
            ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}

      - name: Deployment summary
        shell: bash
        run: |
          echo "Deployed ${{ matrix.workflow }} to: ${{ steps.deploy.outputs.deployment_url }}" >> $GITHUB_STEP_SUMMARY
