name: Deploy GenSX Example Workflows

on:
  push:
    branches: [main]
    paths:
      - "examples/client-side-tools/gensx/**"

jobs:
  deploy-client-side-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Map Agent Workflow
        id: deploy
        uses: ./.github/actions/deploy-gensx
        with:
          org: gensx
          working_directory: examples/client-side-tools
          environment_name: prod
          api_key: ${{ secrets.GENSX_API_KEY }}
          workflow_file: gensx/workflows.ts
          env: |
            ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}

      - name: Deployment summary
        shell: bash
        run: |
          echo "Client Side Tools Deploy to: ${{ steps.deploy.outputs.deployment_url }}" >> $GITHUB_STEP_SUMMARY
