name: Deploy GenSX Example Workflows

on:
  push:
    branches: [main]
    paths:
      - "examples/client-side-tools/gensx/**"
      - "examples/chat-ux/gensx/**"
      - "examples/draft-pad/gensx/**"
      - "examples/deep-research/gensx/**"

jobs:
  deploy-workflows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow:
          - "examples/client-side-tools"
          - "examples/chat-ux"
          - "examples/draft-pad"
          - "examples/deep-research"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Workflow
        id: deploy
        uses: ./.github/actions/deploy-gensx
        with:
          org: gensx
          working_directory: ${{ matrix.workflow }}
          environment_name: prod
          api_key: ${{ secrets.GENSX_API_KEY }}
          workflow_file: gensx/workflows.ts
          env: |
            ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}

      - name: Deployment summary
        shell: bash
        run: |
          echo "Client Side Tools Deploy to: ${{ steps.deploy.outputs.deployment_url }}" >> $GITHUB_STEP_SUMMARY
